Numpy-de Escalares a Tensores

In [4]:
!pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
print ("Array Numpy", arr)
print("Dimensiones del array:", arr.ndim)

Array Numpy [1 2 3 4 5]
Dimensiones del array: 1


In [8]:
arr = np.array([1,2,3,4,5])
print ("Array Numpy", arr)

Array Numpy [1 2 3 4 5]


Primero tenemos un escalar con numpy

In [10]:
escalar= np.array([23])
print("escalar:", escalar)

escalar: [23]


Ahora un vector o un array

In [11]:
vector = np.array([1,2,3,4,5,6,7])
print("vector: ",vector)

vector:  [1 2 3 4 5 6 7]


matrices

In [12]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


tensor

In [13]:
tensor= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


matriz identidad

In [16]:
identidad= np.eye(5)
print(identidad)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


matriz diagonal

In [18]:
diagonal= np.diag([4,4])
print(diagonal)

[[4 0]
 [0 4]]


randoms

In [22]:
random=np.random.random((2,4))
print(random)

[[0.37509718 0.47431626 0.08895367 0.90648415]
 [0.40213217 0.71931099 0.99905612 0.58924466]]


arrays memtodos mas usados

In [27]:
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.ndim)
print(array.shape)
print(array.dtype)

##convertimos los enteros a float

arrayFloat= array.astype(np.float64)
print(arrayFloat)
##sumamos los elementos del array
suma=np.sum(array)
media=np.mean(arrayFloat)
desviacion=np.std(arrayFloat)
print(suma)
print(media)
print(desviacion)

2
(3, 3)
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
45
5.0
2.581988897471611
